# Generated by Django 2.1.7 on 2019-03-26 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('idRoomNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Access', models.CharField(max_length=7)),
                ('Host', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='RoomNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Rooms'),
        ),
        migrations.AddField(
            model_name='guest',
            name='UserEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
    ]
