# Generated by Django 2.1.7 on 2019-03-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190326_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomNumber', models.IntegerField()),
                ('SongURL', models.CharField(max_length=255)),
                ('Index', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('RoomNumber', 'SongURL', 'Index')},
        ),
    ]
