# Generated by Django 2.1.7 on 2019-03-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
