# Generated by Django 2.1.7 on 2019-03-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190327_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(max_length=6),
        ),
    ]
