# Generated by Django 2.1.7 on 2019-03-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190327_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='RoomName',
            field=models.CharField(default='my-room', max_length=45),
        ),
    ]
