# Generated by Django 2.1.7 on 2019-03-28 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190327_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='users',
            name='Nickname',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='users',
            name='Phone',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
