# Generated by Django 2.1.7 on 2019-04-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190328_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
