# Generated by Django 2.1.7 on 2019-03-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190328_0407'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('UserEmail', 'RoomNumber')},
        ),
    ]
