# Generated by Django 2.1.7 on 2019-03-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190328_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=45, unique=True),
        ),
    ]
