# Generated by Django 2.1.7 on 2019-04-05 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190405_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='RoomNumber',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='UserEmail',
        ),
    ]
