# Generated by Django 2.1.7 on 2019-04-07 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190405_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rooms'),
        ),
        migrations.AddField(
            model_name='guest',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Users'),
        ),
    ]
