# Generated by Django 2.1.7 on 2019-03-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190328_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='UserEmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Users', to_field='Email'),
        ),
    ]
