# Generated by Django 2.1.7 on 2019-03-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190329_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='Access',
        ),
        migrations.AddField(
            model_name='rooms',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
