# Generated by Django 2.1.7 on 2019-03-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190329_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='isPrivate',
        ),
        migrations.AddField(
            model_name='rooms',
            name='Access',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
