# Generated by Django 2.1.7 on 2019-03-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190329_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Nickname',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
    ]
